1 – Crie
um array NumPy
com valores de 0 a 11, faça um reshape deste array para uma matriz 3x4. Utilizando
indexação, imprima:
•Toda
a segunda linha.
•O
valor localizado na terceira linha, quarta coluna.

In [ ]:
import numpy as np
arr= np.array([0,1,2,3,4,5,6,7,8,9,10,11])
arr = arr.reshape(3,4)
print(arr)
print(arr[1],arr[2,3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7] 11


2 – Crie dois arrays 1D NumPy com valores [1, 2, 3] e [4, 5, 6] e concatene-os formando um único array. Após isso, faça slicing para obter apenas os elementos [2, 3, 4, 5].

In [10]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

arr= np.concatenate((ar1,ar2))
print(arr[1:])

[2 3 4 5 6]


3 – Crie um array original com valores [10, 20, 30, 40, 50].  Faça uma cópia deste array.  Remova o elemento 30 da cópia sem alterar o
original.  Imprima os dois arrays para mostrar que o original permanece inalterado.

In [11]:
ar1=np.array([10,20,30,40,50])
ar2= ar1.copy()

ar2 = np.delete(ar2,2)
print(ar1,ar2)

[10 20 30 40 50] [10 20 40 50]


4 – Crie
um array com valores [100, 200, 300, 400, 500, 600], divida-o (split) esse array em dois arrays separados, cada um com três elementos.  
No segundo array resultante, adicione o valor700 ao final. Imprima ambos arrays finais.

In [3]:

arr= np.array(([100,200,300,400,500,600]))
ar1= np.array(arr[:3])
ar2= np.array(arr[3:])
ar2 = np.append(ar2,700)
print(arr)
print(ar1)
print(ar2)

[100 200 300 400 500 600]
[100 200 300]
[400 500 600 700]
