In [4]:
import numpy as np

import time
import sys

S= range(1000)

print(sys.getsizeof(S)*len(S))


D= np.arange(1000)
print(D.size*D.itemsize)

48000
8000


In [10]:

a = np.array([(1,2,3),(4,5,6)])

#so chamar a var printa todo contedo dentro dela
print(a)
#.shape mostra dimensão do array 2 listas com 3 itens log 2x3
print(a.shape)
#.ndim conta quantas dimensões possui
print(a.ndim)
#.size mostra o tanto de itens que possui
print(a.size)




[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [ ]:
a = np.array([(1,2,3,4,5,6)])
#.reshape quebra o array na dimensão escrita 
new_arr = a.reshape(2,3)
print(new_arr)
#.copy copia o array  
new_arr = np.copy(a)
#.concatenate(a) concatena dois arrays
#.split(a) divide e  


[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([(1,2,3,4,5,6)])

